# EMBEDDED SERVER CONFIGURATION
server:
    port: ${port:8083}
    context-path: /auth/
    use-forward-headers: true
    error.whitelabel.enabled: false
    compression:
      enabled: true
      min-response-size: 1024
      mime-types:
          - text/html
          - text/css
          - text/plain
          - text/xml
          - application/json
          - application/javascript
# PROFILES
spring:
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost/fotix
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application.name: fotix-auth
  profiles.active: prod
# EUREKA
eureka:
  instance:
      hostname: localhost
      port: 8081
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
# LOGGING
logging.level.org.springframework.security: DEBUG
